#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Air Quality Monitoring"
  Arduino IoT Cloud Variables:
    String message;
    CloudPercentage airquality;
    CloudPercentage humidity;
    CloudTemperature temperature;

  Hardware:
    - ESP32 Dev Module
    - MQ-135 Gas Sensor (analog output -> GPIO34)
    - DHT11 Temperature & Humidity Sensor (data -> GPIO5)
*/

#include "thingProperties.h"
#include "DHT.h"

#define DHTpin 5          // DHT11 data pin connected to ESP32 GPIO 5
#define DHTTYPE DHT11

DHT dht(DHTpin, DHTTYPE);
int sensor = 34;          // MQ-135 analog output connected to ESP32 GPIO 34

void setup() {
  // Start serial communication for debugging
  Serial.begin(9600);
  delay(1500);

  // Initialize the DHT11 sensor (required before reading)
  dht.begin();

  // Initialize cloud variables defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  // Print detailed connection/debug info to Serial Monitor
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();

  // Read humidity and temperature from DHT11
  float hm = dht.readHumidity();
  float temp = dht.readTemperature();

  // Check if the reading was successful
  if (!isnan(hm) && !isnan(temp)) {
    humidity = hm;
    temperature = temp;
    Serial.print("Humidity: ");
    Serial.println(humidity);
    Serial.print("Temperature: ");
    Serial.println(temperature);
  } else {
    Serial.println("Failed to read from DHT11 sensor!");
  }

  // Read raw analog value from MQ-135 (range: 0-4095 on ESP32)
  int airqualityRaw = analogRead(sensor);

  // Convert raw value to a 0-100 percentage scale for display
  int airqualityPercent = map(airqualityRaw, 0, 4095, 0, 100);

  // Clamp the value just in case map() goes slightly out of range
  airqualityPercent = constrain(airqualityPercent, 0, 100);

  airquality = airqualityPercent;

  Serial.print("Gas Value (raw): ");
  Serial.println(airqualityRaw);
  Serial.print("Air Quality (%): ");
  Serial.println(airqualityPercent);

  // Build a combined status message
  message = "Temperature = " + String(temp) + " C  Humidity = " + String(hm) + "%  Air Quality = " + String(airqualityPercent) + "%";

  // Delay to avoid flooding the cloud and to let the DHT11 rest
  delay(2000);
}

void onMessageChange()  {
  // Runs when the "message" variable changes from the Cloud
}

void onAirqualityChange()  {
  // Runs when the "airquality" variable changes from the Cloud
}

void onHumidityChange()  {
  // Runs when the "humidity" variable changes from the Cloud
}

void onTemperatureChange()  {
  // Runs when the "temperature" variable changes from the Cloud
}
